//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Loust.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Loust.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All processes are dead.
        /// </summary>
        internal static string AllProcessesAreDead {
            get {
                return ResourceManager.GetString("AllProcessesAreDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to confirm status to Tash from a non-UI thread.
        /// </summary>
        internal static string ConfirmationToTashNotFromUiThread {
            get {
                return ResourceManager.GetString("ConfirmationToTashNotFromUiThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not confirm status to Tash (error code: {0}).
        /// </summary>
        internal static string CouldNotConfirmStatusToTash {
            get {
                return ResourceManager.GetString("CouldNotConfirmStatusToTash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Tash.
        /// </summary>
        internal static string CouldNotConnectToTash {
            get {
                return ResourceManager.GetString("CouldNotConnectToTash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not make Tash registration (error code: {0}).
        /// </summary>
        internal static string CouldNotMakeTashRegistration {
            get {
                return ResourceManager.GetString("CouldNotMakeTashRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution of script failed: {0}.
        /// </summary>
        internal static string ExecutionOfScriptError {
            get {
                return ResourceManager.GetString("ExecutionOfScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to kill uncontrollable processes.
        /// </summary>
        internal static string FailedToKillProcesses {
            get {
                return ResourceManager.GetString("FailedToKillProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing uncontrollable processes.
        /// </summary>
        internal static string KillingProcesses {
            get {
                return ResourceManager.GetString("KillingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localhost is not available.
        /// </summary>
        internal static string LocalHostNotAvailable {
            get {
                return ResourceManager.GetString("LocalHostNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;Oust.
        /// </summary>
        internal static string LoustWindowTitle {
            get {
                return ResourceManager.GetString("LoustWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code coverage for: {0}.
        /// </summary>
        internal static string NoCoverageFor {
            get {
                return ResourceManager.GetString("NoCoverageFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No process shook hands with Tash.
        /// </summary>
        internal static string NoProcessShookHandsWithTash {
            get {
                return ResourceManager.GetString("NoProcessShookHandsWithTash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tash connection has not yet been established.
        /// </summary>
        internal static string NotConnectedToTashYet {
            get {
                return ResourceManager.GetString("NotConnectedToTashYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the application and visit sodwat.
        /// </summary>
        internal static string PleaseCloseTheApplication {
            get {
                return ResourceManager.GetString("PleaseCloseTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run script recovery if necessary.
        /// </summary>
        internal static string PleaseRunScriptRecoveryManually {
            get {
                return ResourceManager.GetString("PleaseRunScriptRecoveryManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process is busy, please retry later.
        /// </summary>
        internal static string ProcessIsBusy {
            get {
                return ResourceManager.GetString("ProcessIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to restart process.
        /// </summary>
        internal static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running script &apos;{0}&apos;....
        /// </summary>
        internal static string RunningScript {
            get {
                return ResourceManager.GetString("RunningScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script executed without errors.
        /// </summary>
        internal static string ScriptExecutedWithoutErrors {
            get {
                return ResourceManager.GetString("ScriptExecutedWithoutErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script executed without errors.
        /// </summary>
        internal static string ScriptExecutedWithoutErrors1 {
            get {
                return ResourceManager.GetString("ScriptExecutedWithoutErrors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loust script execution.
        /// </summary>
        internal static string ScriptExecution {
            get {
                return ResourceManager.GetString("ScriptExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script execution failed: {0}.
        /// </summary>
        internal static string ScriptExecutionError {
            get {
                return ResourceManager.GetString("ScriptExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script execution failed, no details available.
        /// </summary>
        internal static string ScriptExecutionErrorWithoutMessage {
            get {
                return ResourceManager.GetString("ScriptExecutionErrorWithoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script recovery ended.
        /// </summary>
        internal static string ScriptRecoveryEnded {
            get {
                return ResourceManager.GetString("ScriptRecoveryEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recover from script failure.
        /// </summary>
        internal static string ScriptRecoveryFailed {
            get {
                return ResourceManager.GetString("ScriptRecoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server is not available.
        /// </summary>
        internal static string SqlServerNotAvailable {
            get {
                return ResourceManager.GetString("SqlServerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to recover from script failure.
        /// </summary>
        internal static string StartScriptRecovery {
            get {
                return ResourceManager.GetString("StartScriptRecovery", resourceCulture);
            }
        }
    }
}
